### ISSUE TITLE
after ctnr-f key-bindings stuck

### ISSUE THREAD

**Issue by olisnr** [StefanSchippers/xschem#134] opened 2023-10-24 08:45 UTC
if i select a few models via the `ctrl-f` search, and try to use `m` or `q` to move or change the selection, it wont work. but the menu-commands are working. 
is this some focus-problem? or is it intended?

**Comment by StefanSchippers** [comment] 2023-10-24 08:52
If you use ctrl-f the default is to just highlight the matching elements. You can change this by checking the Select checkbox. After selecting the matching elements I am able to move, delete or change ('q') their attributes. Can you please explain better what is your problem? in some cases the UI is blocked because there is some dialog box that has not been closed (may be obscured or minimized) , please check that too.

**Comment by olisnr** [comment] 2023-10-24 09:20
![1](https://github.com/StefanSchippers/xschem/assets/120017377/5f53ba10-04ae-4923-880a-31bb79f62d85)

then i press `ctnr-f`

![2](https://github.com/StefanSchippers/xschem/assets/120017377/9496f4c7-fe41-4d67-a058-1adff4d44c63)

then i click `ok`

![3](https://github.com/StefanSchippers/xschem/assets/120017377/08561aa3-94d7-4aa7-9a23-a30bec3e5d3c)

now all i wanted is selected, but if i press `q` nothing happens. but the menue `Properties/Edit` is working

**Comment by olisnr** [comment] 2023-10-24 09:23
ups, now i see: somehow the focus is changing to an other program... after closing the search box an other process has the focus. my be some cinnamon problem?

**Comment by olisnr** [comment] 2023-10-24 09:25
may be its because the dialog isnt modal?

**Comment by StefanSchippers** [comment] 2023-10-24 09:25
I will do some tests with other window managers.

**Comment by StefanSchippers** [comment] 2023-10-24 09:30
I tested with **fvwm3** (my window manager) and **icewm** (in its default configuration, which is click-to-focus) and xschem remains focused after a search (ctrl-f)

**Comment by StefanSchippers** [comment] 2023-10-24 09:41
Anyway I think the search dialog box does an unnecessary `grab set` (to force it to be in focus) that is probably unnecessary. This will make xschem responsive (to zoom/pan commands for example) even if the search dialog box is open. This dialog box is configured to remain on top of the xschem window, to avoid it to be obscured. Will remove this historic grab set, since I think it is not needed.

**Comment by olisnr** [comment] 2023-10-24 09:42
its switching to the system-monitor only if the `always on top` option is active. this seems to happen with every dialog-box, but it attract my attention only after the search.

**Comment by StefanSchippers** [comment] 2023-10-24 09:50
So if you close a dialog box in xschem (like the Load/Save As dialog) focus goes to another application? this is weird...

**Comment by StefanSchippers** [comment] 2023-10-24 10:07
Xschem Dialog boxes are configured to be on top of xschem window.
If xschem is set to 'always on top' may be there will be a contention of windows pretending to be on top, and the window manager detects the situation and moves focus away. Just a guess.

**Comment by olisnr** [comment] 2023-10-24 10:40
_So if you close a dialog box in xschem (like the Load/Save As dialog) focus goes to another application? this is weird..._

yes, but the focus goes only to an other application that has the `always on top` flag set.

**Comment by olisnr** [comment] 2023-10-24 10:43
if i also enable `always on top` for Xschem, then the dialogboxes will appear in the back of Xschem, but the focus still goes to the system-monitor after closing

**Comment by StefanSchippers** [comment] 2023-10-24 11:04
I see there are some issues on cinnamon with always on top windows. 
https://github.com/linuxmint/Cinnamon/issues/4386
https://github.com/linuxmint/Cinnamon/issues/4312
https://github.com/linuxmint/cinnamon/issues/10364
https://github.com/linuxmint/cinnamon/issues/10173

**Comment by StefanSchippers** [comment] 2023-10-24 11:06
I see there is (or was) a "`prevent focus stealing`" setting in the desktop. Is this available? can you test if it makes a difference?

**Comment by olisnr** [comment] 2023-10-24 12:07
there is no robbery-prevention anymore:

![win](https://github.com/StefanSchippers/xschem/assets/120017377/bfb31fb9-8e61-4a32-94d9-4ebd7af36a61)

and "Attach dialog wi...". i will try it on the mate desktop...

**Comment by olisnr** [comment] 2023-10-24 13:16
now i installed `fvmw` and `mate` on linuX mint (ubuntu 22.04) and:
mate behaves like cinnamon
fvmw behaves correct

**Comment by StefanSchippers** [comment] 2023-10-24 13:18
Would be nice to see some other application which pops a dialog box and see if there is a similar problem. 
If not then I will like to investigate how to avoid that....

**Comment by olisnr** [comment] 2023-10-24 13:37
i think it could be some Tk/Tcl thing:
i downloaded an other program: `https://aplsimple.github.io/en/tcl/alited/index.html`...
and it does the same...

**Comment by olisnr** [comment] 2023-10-24 13:38
programs like `xed` dont do this

**Comment by StefanSchippers** [comment] 2023-10-24 15:03
Can you please test the following `test.tcl` program? it shows a main window and a button to open a dialog. Set the main window in focus (you will see a cursor in the text area) , then open the dialog box, close it and see if text area is still in focus.
Invoke the program with `wish test.tcl`
```
proc dialog {} {
  toplevel .a
  text .a.t
  .a.t insert 1.0 {Hello, World!}
  button .a.ok -text OK -command {destroy .a}
  pack .a.t .a.ok
  tkwait window .a
}

text .t
.t insert 1.0 {Main window}
button .close -text Close -command { destroy .}
button .dialog -text {Open dialog} -command {dialog}
pack .t
pack .dialog .close -side left

```

**Comment by olisnr** [comment] 2023-10-25 08:37
yes, this code also let the "always top" marked process steal the focus.

**Comment by StefanSchippers** [comment] 2023-10-26 07:37
I also tried setting some apps on top in ICEWM and i can't see this focus stealing problem.

https://github.com/StefanSchippers/xschem/assets/69359491/18a07f1b-0a8c-4d0d-83d5-a11e33b1dee0

**Comment by StefanSchippers** [comment] 2023-10-26 07:43
If you start xschem from a console, can you please issue this command:
xschem [~] **tk_focusFollowsMouse**
and see if the focus stealing still happens?

**Comment by olisnr** [comment] 2023-10-26 08:58
it dont change anything


https://github.com/StefanSchippers/xschem/assets/120017377/04255e7f-5caf-4161-a01d-aae22d9300fb

**Comment by StefanSchippers** [comment] 2023-10-26 13:13
Does the focus robbery happen with any application that is on the 'always on top' layer or only with the system monitor?
In the latter case are there options in System Monitor to change this?

**Comment by StefanSchippers** [comment] 2023-10-26 14:55
I think I need to do some tests on a live Cinnamon Mint image.

**Comment by StefanSchippers** [comment] 2023-10-26 16:43
OK, I got the same problem on Cinnamon, ( I also got the garbage on screen , but adding  the xorg.conf this was fixed right away)
I also found a fix for the problem. Please can you test this modified `test.tcl `program? run it as usual as `wish8.6 test.tcl`
The only change is the addition of `wm transient .a .` in the dialog creation routine. If that works I will apply this to all xschem dialogs.

```
proc dialog {} {
  toplevel .a -class dialog
  wm transient .a .
  text .a.t
  .a.t insert 1.0 {Hello, World!}
  button .a.ok -text OK -command {destroy .a}
  pack .a.t .a.ok
  update
  tkwait window .a
}

text .t
.t insert 1.0 {Main window}
button .close -text Close -command { destroy .}
button .dialog -text {Open dialog} -command {dialog}
pack .t
pack .dialog .close -side left
```

**Comment by olisnr** [comment] 2023-10-26 17:21
yes, this is a working Robbery Prevention...

**Comment by olisnr** [comment] 2023-10-26 17:24
the " I also got the garbage on screen" is the driver-problem? how did You get rid of it?

**Comment by StefanSchippers** [comment] 2023-10-26 17:43
For this machine (an asus core i7 with an intel GPU) it is a matter of disabling the PageFlip.
```
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
```

```
 Section "Device"
     Identifier  "intel"
     Driver      "intel"
     Option "PageFlip" "false"
 EndSection
```

**Comment by StefanSchippers** [comment] 2023-10-26 17:47
I will now start cinnamon on a samsung laptop with a AMD/radeon GPU and see how the patched xschem works.

**Comment by StefanSchippers** [comment] 2023-10-26 18:41
On the old Samsung I can set the xorg.con to work fine  either for xschem (no garbage in xschem, garbage in the desktop background) or for cinnamon (no garbage in the background, garbage in xschem)
The problem is that cinnamon uses OpenGL compositing by default and on these old computers OpenGL is full of bugs.
This computer is simply too old for a modern desktop Linux.

**Comment by olisnr** [comment] 2023-10-27 12:06
yes, i also think i would be good, if users dont need to be aware of the software-problems of there video-drivers. to the speed of Xschem: the biggest refresh break i saw until now are the graph-rectangles if data are loaded and plotted. 
i think the plots should be blanked while zooming or moving and redrawn only after the screen section.

**Closed** 2023-11-02 11:17 UTC
