### ISSUE TITLE
Crash after wrong use of --script

### ISSUE THREAD

**Issue by aschauerf** [StefanSchippers/xschem#109] opened 2023-06-19 17:57 UTC
xschem starts and works after starting with wrong command-line options:

xschem --script $ASIC_BASE_DIR/open_pdks/sky130/sky130A/libs.tech/xschem/xschemrc

(correct:
xschem --rcfile $ASIC_BASE_DIR/open_pdks/sky130/sky130A/libs.tech/xschem/xschemrc
)

but a Segmentation fault (core dumped) occurs when a schematic is tried to be opened or saved.

**Comment by StefanSchippers** [comment] 2023-06-19 18:19
Thank you for this report. will investigate and add the necessary guards

Il Lun 19 Giu 2023, 19:57 aschauerf ***@***.***> ha scritto:

**Comment by StefanSchippers** [comment] 2023-06-19 21:52
It is now fixed, was a regression due to changes done in 89d90c21dba1e70f39aaa1058b1e3e1e0436a6a9
If you have a chance to test please do it. 
Using --script for an rcfile will not prevent xschem to read the standard xschemrc file (if existing) in ~/.xschem/xschemrc, in this case you end up starting xschem with 2 xschemrc files sourced. This could lead to a mix of different paths or settings, but program should behave normally and not crash.
--rcfile for loading an xschemrc file is a better option since it prevents xschem from loading any other (default) xschemrc file

**Closed** 2023-06-29 19:59 UTC
