### ISSUE TITLE
move and stretch shows a little problem with labels

### ISSUE THREAD

**Issue by olisnr** [StefanSchippers/xschem#124] opened 2023-09-26 13:00 UTC
i want to be able to move parts without changing the connections. but in the moment it dont work for net-labels

my xschemrc have now:

```
set replace_key(Control-z) u        ;# undo
set replace_key(Control-y) Shift-U  ;# redo
set replace_key(z) Control-z        ;# zoom out
set unzoom_nodrift 1
set draw_crosshair 1
set persistent_command 1 #for click instead of w

set enable_stretch 1 #for preserve the connections
set connect_by_kissing 1 #for preserve the connections
set unselect_partial_sel_wires 1 #for preserve the connections
```
![1](https://github.com/StefanSchippers/xschem/assets/120017377/b93a6120-0491-4318-90d4-5b94903fb9d9)
select v2
![2](https://github.com/StefanSchippers/xschem/assets/120017377/26513d47-7f1a-4f94-a137-4f48788075a6)
move v2
![3](https://github.com/StefanSchippers/xschem/assets/120017377/ef9c069e-fed5-4f55-9b62-2bf0ab47e29c)
place v2
![4](https://github.com/StefanSchippers/xschem/assets/120017377/167bb597-1a05-4c38-9097-a02b3dd4548a)

the label isnt connected anymore.

i think, that may be there should be only two options: moving parts and wire fragments and destroy the connections or moving parts and stretching wires, without destroying any connection. 

it could be two different commands "move" and "drag" like in LTspice. then the options "enable stretch", "unsel parital sel..." and "auto join..." wouldent be needed anymore, because they would be set to "move and break" or "drag and preserve".

what do You think?

**Comment by StefanSchippers** [comment] 2023-09-26 16:35
There is a nice command Tools-> Break wires at selected instance pins (! keybind).
You select some components / labels (or even everything, ctrl-a) and press !.

This will allow following (stretch) move of the component to preserve label connections. see image. 

![1](https://github.com/StefanSchippers/xschem/assets/69359491/8c521dec-aa00-4c56-ae1a-001f1a57d99b)

I think more elaborate things can be done, but these will be deferred after 3.4.4 release.

**Comment by StefanSchippers** [comment] 2023-09-26 16:59
Another interesting command is 'Shift-M'. This will not stretch wires, it will add new wires at the terminals when movimg a component.
![1](https://github.com/StefanSchippers/xschem/assets/69359491/d880cdee-7277-4028-b195-c58c3658c531)

**Comment by olisnr** [comment] 2023-09-26 21:46
yes shift-m is also useful.  

and all this changes are very useful for me. 
but some things are still strange. i think, if every pin would automatic brake the wires, the experience would be much more constant. some option` brake_wire_on_pin` like the `connect_by_kissing` could save the connections.

now You can have this:

draw a wire
![a](https://github.com/StefanSchippers/xschem/assets/120017377/7a2a1a4b-f64d-48ae-a68f-8c024fb23127)

add two parts
![b](https://github.com/StefanSchippers/xschem/assets/120017377/09b70a32-ff24-4cf9-9880-4f02a3660cb3)

move one
![c](https://github.com/StefanSchippers/xschem/assets/120017377/32464772-5f1d-4593-a6f1-18b256890cc9)

move the other
![d](https://github.com/StefanSchippers/xschem/assets/120017377/e85a69c4-a68f-4455-a9ad-b73cfdaa859c)

be amazed
![e](https://github.com/StefanSchippers/xschem/assets/120017377/28627d9e-f85c-4a13-9ed5-cd13dbe58efd)

**Comment by olisnr** [comment] 2023-09-26 21:57
its also possible to use `cntr-a` and `!` every time before selecting and dragging, but...

anyway, i dont want to disturb the release of 3.4.4 and if can use help whit something may be testing...

**Comment by StefanSchippers** [comment] 2023-09-26 22:09
Please tell me the exact setup and commands, i can't get this strange result shown above :-)
![1](https://github.com/StefanSchippers/xschem/assets/69359491/0320afb1-89cc-4f9d-8533-2ec31aa60aac)

**Comment by olisnr** [comment] 2023-09-26 23:39
i used #define FIX_BROKEN_TILED_FILL 1 & enabled option-menue-entries:
undue....
enable...
unsel...
autojoin...
persistent...

but i think the question is if the wire ends on a pin or not. in my example the ADC-block in the north connects to a wire goes higher then the highest pin, while in the south the last pin and the endpoint of the wire are at the same point

**Comment by StefanSchippers** [comment] 2023-09-26 23:54
I have tried again and can't see the problem.I remember there was a similar issue some days ago but it was fixed. Ensure you update your xschem workspace and rebuild the latest commit.


https://github.com/StefanSchippers/xschem/assets/69359491/8b8b833f-79e6-456a-87af-f59b7c4036b3

**Comment by olisnr** [comment] 2023-09-27 07:31
yes , i did use the latest version (before the new GPU-fix in the menue). 
BUT i did use the m command, because i enabled the "enable stretch" from the option menue. and this should switch the exchange the m and the cntr-m command.
may be that is somehow broken now. i remember it was working in an older version.

**Comment by olisnr** [comment] 2023-09-27 07:34
if i remove the "enable stretch" it also stretches the wires a the m command.

**Comment by StefanSchippers** [comment] 2023-09-27 07:43
Sorry I can not reproduce **any** of these things.
Without **enable stretch** 'm' moves the part only, if only the part is selected.

**Comment by StefanSchippers** [comment] 2023-09-27 07:44
may be the german keyboard add some problems here.

**Comment by olisnr** [comment] 2023-09-27 08:55
You are right.
i tried the version form yesterday night without cross-hair and without the precompiler driver fix, and this didnt change anything.
then i changed my keyboard from german (swiss) to english (US) and the cntr-key istnt working anymore in xschem also the zooming via the scroll-weel of the mouse.

what keyboard setting do You use?

and why did it work before? has something changed whit the key-binding code?

i will test more at the newest version (the one with the fix in the menue) later

**Comment by StefanSchippers** [comment] 2023-09-27 09:31
I have US keyboard

**Comment by olisnr** [comment] 2023-09-27 10:17
i can choose from 4 different us layouts :)

![keyb](https://github.com/StefanSchippers/xschem/assets/120017377/ab3377fc-9c7d-4f99-a615-c3f7d8b37438)

**Comment by olisnr** [comment] 2023-09-27 10:32
now i downloaded the newest version, and its really strange: if i use english (us) not only the zoom scroll from the mouse dont work anymore, also the `c`  `q` and `m` command does not work. aaaaand the right click context-menue is also missing.

may be its a problem in combination whit cinnamon... i try to test mate also. i could also try different keyboard layouts. what should i test? and what does the "debug mode"? writing some intersting log-file?

**Comment by olisnr** [comment] 2023-09-27 10:33
the 'esc' and 'del' commands are working in the US layout

**Comment by StefanSchippers** [comment] 2023-09-27 10:35
The only way i can mess up things that badly is if Caps-Lock is set

**Comment by olisnr** [comment] 2023-09-27 10:35
no, You mad it very clear, if its set :)

**Comment by StefanSchippers** [comment] 2023-09-27 10:36
if you are using an external keyboard on a laptop sometimes the external keyboard and the internal are  notin sync, it happened sometimes., very rarely, i have to disconnect the usb and reset the external keyboard

**Comment by olisnr** [comment] 2023-09-27 10:37
i will try, but a strange thing is, the external trackball also change the functionality if i change the keyboard layout

**Comment by olisnr** [comment] 2023-09-27 10:38
i dont have an external keybord, but i can search one to test it. but that wasent what You asked for

**Comment by StefanSchippers** [comment] 2023-09-27 10:39
Otherwise the desktop environment is messing up things in the worst possible way. I don't use desktop environments at all. All i do to change the keyboard layout is `setxkbmap -layout us`, `setxkbmap -layout de`.

**Comment by StefanSchippers** [comment] 2023-09-27 13:25
Going gack to the original problem of garbage on the screen, can you please
update xschem to latest and test again without the "fix_broken_tiled_fill"?
I found a regression introduced many commits ago. Fixed now.

**Comment by olisnr** [comment] 2023-09-27 13:35
Yes the GPU-driver-fix works great! what does the "no xcopy area ..." do?

the keyboard-layout problem has something to do whit the destktop-manager i think because, if i change the keyboard from the terminal it does whats expected:
`setxkbmap -layout us`  `setxkbmap -layout de`   `setxkbmap -layout ch` all do the same (only .us exchanges Z with Y), but the rest stays working if i use the swiss-german keyboard from the keyboard dialog, or dont work if i use the english (us) layout.

do You have an idea how to debbug this? is there an event log i can enable?

**Comment by olisnr** [comment] 2023-09-27 14:19
if i see this right, xschem gets the current pressed key in from the function callback, that gets ist from a TCL code. but who ist it?, and where get he the key-code from?

**Comment by olisnr** [comment] 2023-09-27 14:52
ok i found out :) the dbg enable writes to the stdout...

**Comment by olisnr** [comment] 2023-09-27 15:11
do You have an idea why i cant redirect the log output into a file? it tryed 
```
xschem > log
key=0 EQUAL_MODMASK=0, SET_MODMASK=0
callback(): Event:-55
key=0 EQUAL_MODMASK=0, SET_MODMASK=0
key=0 EQUAL_MODMASK=0, SET_MODMASK=0
draw_crosshair()
draw_selection
```
xschem did make a file named "log" but didnt use it for the output

**Comment by StefanSchippers** [comment] 2023-09-27 15:41
For debug in a log file:

xschem -d 1 -l logfile

**Comment by StefanSchippers** [comment] 2023-09-27 15:43
callback() gets events from tcl. Events are set in tcl with the bind
instruction. See set_binding tcl procedure

**Comment by StefanSchippers** [comment] 2023-09-27 16:19
For debugging events start wish (the tk interpreter), write this one line:

bind . <KeyPress> {puts "%K %s"}

and then do keypresses in the wish toplevel window. You get the key and the state (shift, alt, ...) 
for details: man 3tk bind

**Comment by olisnr** [comment] 2023-09-27 16:21
an interesting thing is: the mouse events are dependent from the GUi-keybord-layout setting: 

english us. zoom in zoom out:
```
callback(): Event:-55
callback(): ButtonPress  ui_state=0 state=8192
callback(): ButtonRelease  ui_state=0 state=10240
callback(): ButtonPress  ui_state=0 state=8192
callback(): ButtonRelease  ui_state=0 state=12288
```
german swiss. zoom in zoom out:
```
callback(): Event:-55
callback(): ButtonPress  ui_state=0 state=0
callback(): ButtonRelease  ui_state=0 state=2048
callback(): ButtonPress  ui_state=0 state=0
callback(): ButtonRelease  ui_state=0 state=4096
```
 
strange...

**Comment by StefanSchippers** [comment] 2023-09-27 16:27
The X11 defines higher mask bits for mouse buttons. If you press a key with button1 (left) pressed you get state=256
mouse button2 gets 512
mouse button 3, (right gets 1024
mouse buttons 4 and 5 (scroll wheel) get 2048 and 4096

higher bits are not defined

in /usr/include/X11/X.h:

```
#define Button1Mask             (1<<8)
#define Button2Mask             (1<<9)
#define Button3Mask             (1<<10)
#define Button4Mask             (1<<11)
#define Button5Mask             (1<<12)

```

**Comment by StefanSchippers** [comment] 2023-09-27 16:28
I can do an interesting thing: at the beginning of callback() function  filter out all bits that are above bit 13 in the state variable...

**Comment by olisnr** [comment] 2023-09-27 16:29
yes this could save us...

**Comment by olisnr** [comment] 2023-09-27 16:35
`state = state & 0x1fff;`

seems to work in the beginning of the callback

**Comment by StefanSchippers** [comment] 2023-09-27 16:38
Yes it is committed now

**Comment by olisnr** [comment] 2023-09-27 16:39
but this donsnt fix the normal mode for me. m and cntr-m are dragging dont care the state of "enable stretch"

how do You this screen-video? i would like to show it

**Comment by StefanSchippers** [comment] 2023-09-28 06:44
It seems state bits above 12 are used for the X Keyboard extension. See the protocol speciication [here](https://www.x.org/releases/X11R7.7/doc/kbproto/xkbproto.html).

**Comment by StefanSchippers** [comment] 2023-09-28 06:59
Can you please test this:
in xinit.c after including xschem.h
add this line:
#include <X11/XKBlib.h>
```#include "xschem.h"
#ifdef __unix__
#include <pwd.h> /* getpwuid */
#endif
#include <X11/XKBlib.h>
...
...
```
Then after ` X INITIALIZATION` add:
XkbIgnoreExtension(True);

```
/*                      */
 /*  X INITIALIZATION    */
 /*                      */
 if( has_x ) {
    mainwindow=Tk_MainWindow(interp);
    if(!mainwindow) {
       fprintf(errfp, "Tcl_AppInit() err 6: Tk_MainWindow returned NULL...\n");
       return TCL_ERROR;
    }
    display = Tk_Display(mainwindow);
    XkbIgnoreExtension(True);
    ...
    ...
```
and see if the strange high order bits are still causing problems.

**Comment by olisnr** [comment] 2023-09-28 08:03
it dont change anything. i think the state numbers are fixed with the bit-mask.

i made a video showing the behavior of my version of xschem:

https://github.com/StefanSchippers/xschem/assets/120017377/e780f3aa-96df-4057-ad8f-6c2b3cc6f662

**Comment by StefanSchippers** [comment] 2023-09-28 08:25
This is all correct and as intended. When you move the right AO21 the net that lands on the bottom pin follows the instance while moving.

**Comment by olisnr** [comment] 2023-09-28 09:19
i deleted my xschemrc file, and then its working as on Your video. then i found that the option: `set connect_by_kissing 1 ;#for preserve the connections` does change the non-strechting `m` command to a stretching one. or in other words, if i enable the kissing im not able anymore to move the parts non-stretching. 
i would think, the kissing should connect all toutching pins, but not change the standard moving command. what do You think about it?

**Comment by StefanSchippers** [comment] 2023-09-28 09:20
Oh, thank you I will check. I think there are too many options, it is getting a bit messy :-)

**Comment by olisnr** [comment] 2023-09-28 09:26
Yes. its really complex. basically, i would think, two would be enough: moving or dragging. moving breaks all connections and dragging non.

LTspice does this in a good way. altium is bad, virtuoso i dont know... what CAD is Your inspiration?

**Closed** 2023-09-29 16:40 UTC
